CREATE TABLE users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    IsBanned BIT DEFAULT 0,
    IsGuest BIT DEFAULT 0,
    IsOnline BIT DEFAULT 0,
    IsAdmin BIT DEFAULT 0
);

CREATE TABLE topics (
    TopicID INT IDENTITY(1,1) PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Description TEXT,
    CreatedAt DATETIME DEFAULT GETDATE(),
    IsHidden BIT DEFAULT 0
);

CREATE TABLE threads (
    FthreadID INT IDENTITY(1,1) PRIMARY KEY,
    TopicID INT,
    Title VARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    IsLocked BIT DEFAULT 0,
    FOREIGN KEY (TopicID) REFERENCES Topic(TopicID) ON DELETE CASCADE
);

CREATE TABLE posts (
    PostID INT IDENTITY(1,1) PRIMARY KEY,
    FthreadID INT,
    UserID INT,
    Content TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (FthreadID) REFERENCES Thread(FthreadID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE
);